---
- name: "Ansible playbook example"
  hosts: 127.0.0.1
  connection: local
  tasks: 
    - name: Update all packages to their latest version
      become: true
      ansible.builtin.apt:
        name: "*"
        state: latest
